### ISSUE TITLE
ChatAllowedCharacters ASM breaks

### ISSUE THREAD

**Issue by SnowShock35** [coolsquid/SquidUtils#42] opened 2015-06-10 01:33 UTC
http://paste.ee/p/C9ETC

**Comment by coolsquid** [comment] 2015-06-10 15:29
Okay, the issue is caused by IntelliInput doing ASM badly. I've made a temporary fix for this, but I need to find a more permanent solution later.

**Comment by coolsquid** [comment] 2015-06-18 23:30
Blame IntelliInput. I'll see if I talk to the dev later.

**Closed by coolsquid** 2015-06-18 23:30 UTC
Labels: bug, mod interaction, temporary fix
